name: edgefarm-network-operator
on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-push-edgefarm-network-operator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into Docker
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.3"
      - name: Build and Push Docker Images
        run: |
          make docker-build docker-push IMG="ci4rail/network-operator:latest"
          make docker-build docker-push IMG="ci4rail/network-operator:${GITHUB_SHA::8}"
